### ISSUE TITLE
Fibonacci - exception

### ISSUE THREAD

**Issue by MartinMSPedersen** [RichardWarburton/java-8-lambdas-exercises#28]
This code in chapter 5 is not correct:
``
public long fibonacci(int x) {
  return cache.computeIfAbsent(x, n -> fibonacci(n-1) + fibonacci(n-2));
}
``
because you are not allowed to change the cache when you are using _computeIfAbsent()_

**Exception in thread "main" java.util.ConcurrentModificationException**

**Comment by RichardWarburton** [comment]
See discussion on https://github.com/RichardWarburton/java-8-lambdas-exercises/pull/27

**Comment by MartinMSPedersen** [comment]
OK
